    user=models.OneToOneField(User,on_delete=models.CASCADE)
    city=models.ForeignKey('City',related_name='user_city',on_delete=models.CASCADE,blank=True, null=True)
    phone_number=models.CharField(max_length=15, blank=True, null=True)
    image=models.ImageField(upload_to='profile/')
    place=models.CharField(max_length=50)
    phone_number=models.CharField(max_length=20)
    email=models.EmailField(max_length=300)
    owner=models.ForeignKey(User,related_name='job_owner',on_delete=models.CASCADE)
    title=models.CharField(max_length=100)
    job_tybe=models.CharField(max_length=15,choices=JOB_TYPE)
    country = models.CharField(max_length=200,null=True, choices=CountryField().choices + [('', 'Select Country')])
 # Add the country field

    description=models.TextField(max_length=10000)
 
    responsibilities = models.TextField(max_length=10000)
    qualifications = models.TextField(max_length=10000)
    benefits = models.TextField(max_length=10000)
    published_at=models.DateTimeField(auto_now=True)
    Vacancy=models.IntegerField(default=1)
    
    salary=models.IntegerField(default=0)
    experince=models.IntegerField(default=1)
    #category
    category = models.ForeignKey('Category',on_delete=models.CASCADE)
    image=models.ImageField(upload_to=image_upload)
    slug=models.SlugField(blank=True,null=True)
    name=models.CharField(max_length=25)
    job=models.ForeignKey(Job, related_name='apply_job', on_delete=models.CASCADE)
    name=models.CharField(max_length=50)
    email=models.EmailField(max_length=100)
    website=models.URLField(null=True,blank=True)
    cv=models.FileField(upload_to='apply/',)
    cover_letter=models.TextField(max_length=500)
    created_at=models.DateTimeField(auto_now=True)