# Generated by Django 5.0.2 on 2024-03-12 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Jobh',
            new_name='Hjob',
        ),
        migrations.RenameField(
            model_name='hjob',
            old_name='hVacancy',
            new_name='HVacancy',
        ),
        migrations.RenameField(
            model_name='hjob',
            old_name='hcountry',
            new_name='Hcountry',
        ),
        migrations.RenameField(
            model_name='hjob',
            old_name='hdescription',
            new_name='Hdescription',
        ),
        migrations.RenameField(
            model_name='hjob',
            old_name='hexperince',
            new_name='Hexperince',
        ),
        migrations.RenameField(
            model_name='hjob',
            old_name='hjob_tybe',
            new_name='Hjob_tybe',
        ),
        migrations.RenameField(
            model_name='hjob',
            old_name='hpublished_at',
            new_name='Hpublished_at',
        ),
        migrations.RenameField(
            model_name='hjob',
            old_name='hsalary',
            new_name='Hsalary',
        ),
        migrations.RenameField(
            model_name='hjob',
            old_name='hslug',
            new_name='Hslug',
        ),
        migrations.RenameField(
            model_name='hjob',
            old_name='htitle',
            new_name='Htitle',
        ),
    ]
