# Generated by Django 5.0.2 on 2024-03-12 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_rename_jobh_hjob_rename_hvacancy_hjob_hvacancy_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Hjob',
        ),
    ]
