# Generated by Django 5.0.2 on 2024-04-03 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_cv_delete_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
