# Generated by Django 5.0.2 on 2024-04-03 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CV',
        ),
    ]
