# Generated by Django 5.0.2 on 2024-03-06 20:04

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_job_country_alter_job_image_delete_apply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
