# Generated by Django 5.0.2 on 2024-03-15 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_remove_job_experience_remove_job_job_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='benefits',
            field=models.TextField(default=0, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='qualifications',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(default=1, max_length=10000),
            preserve_default=False,
        ),
    ]
