# Generated by Django 5.0.2 on 2024-03-15 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0013_job_benefits_job_qualifications_job_responsibilities'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(max_length=250),
        ),
    ]
