# Generated by Django 5.0.2 on 2024-03-15 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_alter_job_benefits_alter_job_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='benefits',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='job',
            name='qualifications',
            field=models.TextField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='job',
            name='responsibilities',
            field=models.TextField(max_length=10000),
        ),
    ]
