# Generated by Django 5.1.5 on 2025-01-29 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0016_rename_vacancy_job_experience_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='experience',
            new_name='experince',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='job_type',
            new_name='job_tybe',
        ),
    ]
